server:
  port: 10087 # 服务端口 
spring:
  application:
    name: eurekaclient1 # eureka的服务名称
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
#    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true